server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: futa-customer
          uri: lb://futa-customer
          predicates:
            - Path=/futa-customer/**
          filters:
            - StripPrefix=1
        - id: futa-search
          uri: lb://futa-search
          predicates:
            - Path=/futa-search/**
          filters:
            - StripPrefix=1
    nacos:
      #发布到注册中心（注册中心配置）
      discovery:
        # nacos的ip地址和端口
        server-addr: ${NACOS-HOST:127.0.0.1}:${NACOS-PORT:8848}
        # 命名空间id(此处不用public,因public初始化的空间, id为空) 如果找不到NACOS-NAMESPACE 使用liuyu
        namespace: ${NACOS-NAMESPACE:nacos}
        # 命名空间分组
        group: ${NACOS-GROUP:dev}
        #cluster-name: HZ # 集群名称
      # 配置中心
      config:
        # nacos的ip地址和端口
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 命名空间id(此处不用public,因public初始化的空间, id为空) 如果找不到NACOS-NAMESPACE 使用liuyu
        namespace: ${spring.cloud.nacos.discovery.namespace}
        # 命名空间分组
        group: dev
        # 这个就表示 在我们nacos命名空间id为 dev中 有一个data-id 为 demo-service.yml 的配置文件 读取这个里面的配置
        file-extension: yml
        # 支持多个共享 Data Id 的配置，优先级小于extension-configs,
        # 自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。
        # Config 有 3 个属性，分别是 dataId, group 以及 refresh
        shared-configs:
          - data-id: application.${spring.cloud.nacos.config.file-extension} # 配置文件名-Data Id
            group: ${spring.cloud.nacos.discovery.group} # 默认为DEFAULT_GROUP
            refresh: true # 是否动态刷新，默认为false
        name: ${spring.application.name}
      #nacos 用户名和密码
      username: ${NACOS-USERNAME:nacos}
      password: ${NACOS-PASSWORD:nacos}


#eureka:
#  client:
#    service-url:
#      defaultZone: http://futa:futa@127.0.0.1:8761/eureka
#      registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
#  instance:
#    prefer-ip-address: true #是否注册ip地址
#    ip-address: 127.0.0.1   # ip地址